version: "2.4"
services:
  db:
    restart: always
    image: postgres:12.3
    volumes:
      - "./pg_data_dev:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
  web:
    restart: always
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - db
