version: "2.4"
services:
  db:
    restart: always
    image: postgres:12.3
    volumes:
      - "./pg_data_dev:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
  web:
    restart: always
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
    - .:/code
  redis:
    restart: always
    command: redis-server
    image: redis:latest
    ports:
      - "6379:6379"
  worker:
    build: .
    command: celery worker -A rainbow6siege_api -l debug
    volumes:
      - .:/code
    depends_on:
      - web
      - redis
  flower:
    image: mher/flower
    command: flower --broker=redis://redis/2 --port=8888
    ports:
      - 8888:8888
    depends_on:
      - web
      - redis
