# Generated by Django 3.0.4 on 2020-05-15 11:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
            },
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
                ('real_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Real name')),
                ('biography', models.TextField(blank=True, null=True, verbose_name='Biography')),
                ('psychological_profile', models.TextField(blank=True, null=True, verbose_name='Psychological profile')),
                ('position', models.CharField(choices=[('DEF', 'Defender'), ('ATT', 'Attacker')], default='DEF', max_length=3)),
                ('birthplace', models.CharField(blank=True, max_length=200, null=True, verbose_name='Birthplace')),
                ('date_of_birth', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Date of birth')),
                ('height', models.FloatField(blank=True, default=0, null=True, verbose_name='Height')),
                ('weight', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Weight')),
                ('armor_rating', models.CharField(blank=True, choices=[('1', 'Light'), ('2', 'Medium'), ('3', 'Heavy')], default='1', max_length=1, null=True)),
                ('speed_rating', models.CharField(blank=True, choices=[('1', 'Slow'), ('2', 'Normal'), ('3', 'Fast')], default='1', max_length=1, null=True)),
                ('unique_ability', models.CharField(max_length=200, verbose_name='Unique ability')),
                ('organizations', models.ManyToManyField(related_name='operators', to='operators.Organization', verbose_name='Organizations')),
            ],
            options={
                'verbose_name': 'Operator',
                'verbose_name_plural': 'Operators',
            },
        ),
    ]
