# Generated by Django 3.0.4 on 2020-05-16 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0002_auto_20200516_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator',
            name='armor_rating',
            field=models.CharField(blank=True, choices=[('Light', 'Light'), ('Medium', 'Medium'), ('Heavy', 'Heavy')], default='Medium', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='operator',
            name='position',
            field=models.CharField(choices=[('Defender', 'Defender'), ('Attacker', 'Attacker'), ('Both', 'Both')], default='Both', max_length=10),
        ),
        migrations.AlterField(
            model_name='operator',
            name='real_name',
            field=models.CharField(blank=True, default='Unknown', max_length=200, null=True, verbose_name='Real name'),
        ),
        migrations.AlterField(
            model_name='operator',
            name='speed_rating',
            field=models.CharField(blank=True, choices=[('Slow', 'Slow'), ('Normal', 'Normal'), ('Fast', 'Fast')], default='Normal', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='operator',
            name='unique_ability',
            field=models.CharField(default='Missing', max_length=200, verbose_name='Unique ability'),
        ),
    ]
