# Generated by Django 3.0.4 on 2020-05-16 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0004_operator_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator',
            name='height',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='operator',
            name='weight',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Weight'),
        ),
    ]
