# Generated by Django 3.0.4 on 2020-05-17 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0005_auto_20200517_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator',
            name='date_of_birth',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Date of birth'),
        ),
    ]
