# Generated by Django 3.0.4 on 2020-05-17 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0006_auto_20200517_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator',
            name='age',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Age'),
        ),
    ]
