# Generated by Django 3.0.7 on 2020-06-10 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0007_auto_20200517_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
