# Generated by Django 3.0.7 on 2020-06-10 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0008_auto_20200610_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
