# Generated by Django 3.0.4 on 2020-05-15 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operators', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('SI', 'Sight'), ('BAR', 'Barrel'), ('GR', 'Grip'), ('UND_BAR', 'Under Barrel')], default='SI', max_length=7)),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Attachment',
                'verbose_name_plural': 'Attachments',
            },
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('type', models.CharField(choices=[('AS', 'Assault Rifle'), ('SH', 'Shotgun'), ('MA', 'Machine Pistol'), ('GA', 'Gadget'), ('SU', 'Gadget')], default='AS', max_length=2, verbose_name='Type')),
                ('max_ammunition', models.CharField(default='1', max_length=200, verbose_name='Maximum ammunition')),
                ('mobility', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Mobility')),
                ('fire_modes', models.TextField(verbose_name='Fire modes')),
                ('standard_damage', models.CharField(max_length=200, verbose_name='Standard damage')),
                ('suppressed_damage', models.CharField(max_length=200, verbose_name='Standard damage')),
                ('rate_of_fire', models.CharField(max_length=200, verbose_name='Rate of fire')),
                ('magazine_size', models.CharField(max_length=100, verbose_name='Magazine size')),
                ('ammunition_type', models.CharField(max_length=100, verbose_name='Ammunition type')),
                ('affiliation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='operators.Organization', verbose_name='Affiliation')),
                ('barrels', models.ManyToManyField(related_name='barrels', to='weapons.Attachments', verbose_name='Barrels')),
                ('grips', models.ManyToManyField(related_name='grips', to='weapons.Attachments', verbose_name='Grips')),
                ('sights', models.ManyToManyField(related_name='sights', to='weapons.Attachments', verbose_name='Sights')),
                ('under_barrels', models.ManyToManyField(related_name='under_barrels', to='weapons.Attachments', verbose_name='Under Barrels')),
                ('users', models.ManyToManyField(related_name='weapons', to='operators.Operator', verbose_name='Operators')),
            ],
            options={
                'verbose_name': 'Weapon',
                'verbose_name_plural': 'Weapons',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Loadout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Description')),
                ('gadgets', models.ManyToManyField(related_name='loadout_as_gadgets', to='weapons.Weapon', verbose_name='Gadgets')),
                ('operator', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='operators.Operator', verbose_name='Operator')),
                ('primary_weapons', models.ManyToManyField(related_name='loadout_as_primary', to='weapons.Weapon', verbose_name='Primary weapons')),
                ('secondary_weapons', models.ManyToManyField(related_name='loadout_as_secondary', to='weapons.Weapon', verbose_name='Secondary weapons')),
            ],
            options={
                'verbose_name': 'Loadout',
                'verbose_name_plural': 'Loadouts',
            },
        ),
        migrations.CreateModel(
            name='Gadget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('type', models.CharField(choices=[('AS', 'Assault Rifle'), ('SH', 'Shotgun'), ('MA', 'Machine Pistol'), ('GA', 'Gadget'), ('SU', 'Gadget')], default='AS', max_length=2, verbose_name='Type')),
                ('max_ammunition', models.CharField(default='1', max_length=200, verbose_name='Maximum ammunition')),
                ('mobility', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Mobility')),
                ('affiliation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='operators.Organization', verbose_name='Affiliation')),
                ('users', models.ManyToManyField(related_name='gadgets', to='operators.Operator', verbose_name='Operators')),
            ],
            options={
                'verbose_name': 'Gadget',
                'verbose_name_plural': 'Gadgets',
                'abstract': False,
            },
        ),
    ]
