# Generated by Django 3.0.4 on 2020-05-16 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0002_auto_20200516_1213'),
        ('weapons', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loadout',
            name='description',
        ),
        migrations.AlterField(
            model_name='gadget',
            name='type',
            field=models.CharField(choices=[('AS', 'Assault Rifle'), ('SH', 'Shotgun'), ('MA', 'Machine Pistol'), ('GA', 'Gadget'), ('SU', 'Submachine gun')], default='AS', max_length=2, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='gadget',
            name='users',
            field=models.ManyToManyField(related_name='gadgets', to='operators.Operator', verbose_name='Users'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='type',
            field=models.CharField(choices=[('AS', 'Assault Rifle'), ('SH', 'Shotgun'), ('MA', 'Machine Pistol'), ('GA', 'Gadget'), ('SU', 'Submachine gun')], default='AS', max_length=2, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='users',
            field=models.ManyToManyField(related_name='weapons', to='operators.Operator', verbose_name='Users'),
        ),
    ]
