# Generated by Django 3.0.7 on 2020-06-10 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weapons', '0003_auto_20200610_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon',
            name='ammunition_type',
            field=models.CharField(max_length=100, null=True, verbose_name='Ammunition type'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='fire_modes',
            field=models.TextField(null=True, verbose_name='Fire modes'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='magazine_size',
            field=models.CharField(max_length=100, null=True, verbose_name='Magazine size'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='rate_of_fire',
            field=models.CharField(max_length=200, null=True, verbose_name='Rate of fire'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='standard_damage',
            field=models.CharField(max_length=200, null=True, verbose_name='Standard damage'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='suppressed_damage',
            field=models.CharField(max_length=200, null=True, verbose_name='Standard damage'),
        ),
    ]
