# Generated by Django 3.0.7 on 2020-06-10 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weapons', '0004_auto_20200610_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gadget',
            name='type',
            field=models.CharField(choices=[('Assault Rifle', 'Assault Rifle'), ('Marksman Rifle', 'Marksman Rifle'), ('Shotgun', 'Shotgun'), ('Machine Pistol', 'Machine Pistol'), ('Gadget', 'Gadget'), ('Submachine gun', 'Submachine Gun'), ('Handgun', 'Handgun')], default='Assault Rifle', max_length=100, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='type',
            field=models.CharField(choices=[('Assault Rifle', 'Assault Rifle'), ('Marksman Rifle', 'Marksman Rifle'), ('Shotgun', 'Shotgun'), ('Machine Pistol', 'Machine Pistol'), ('Gadget', 'Gadget'), ('Submachine gun', 'Submachine Gun'), ('Handgun', 'Handgun')], default='Assault Rifle', max_length=100, verbose_name='Type'),
        ),
    ]
