# Generated by Django 3.0.7 on 2020-06-10 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weapons', '0005_auto_20200610_0921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gadget',
            name='max_ammunition',
        ),
        migrations.RemoveField(
            model_name='weapon',
            name='fire_modes',
        ),
        migrations.RemoveField(
            model_name='weapon',
            name='max_ammunition',
        ),
    ]
